FROM python:3.6.6-alpine3.6
COPY . /server
WORKDIR /server
RUN apk --update add g++ \
    make \
    postgresql-dev && \
    pip install -r requirements.txt && \
    pip install gunicorn
VOLUME [ "/tmp", \
         "/server/static" ]
CMD [ "gunicorn", \
      "-b", \
      "unix:/tmp/gunicorn.sock", \
      "{{ cookiecutter.project_name }}.wsgi" ]
