FROM python:3.6.6-alpine3.6
ENV PYTHONUNBUFFERED 1
RUN apk --update add g++ \
  make \
  jpeg-dev zlib-dev freetype-dev lcms2-dev openjpeg-dev tiff-dev tk-dev tcl-dev \
  bash git openssh \
  postgresql-dev
WORKDIR /server
COPY ./requirements.txt /server
RUN pip install -r requirements.txt
COPY . /server
EXPOSE {{ cookiecutter.django_dev_port }}
ENTRYPOINT [ "python", "manage.py" ]
CMD [ "runserver", \
    "0.0.0.0:{{ cookiecutter.django_dev_port }}" ]
