FROM python:3.6.6-alpine3.6
ENV PYTHONUNBUFFERED 1
RUN apk --update add g++ \
  make \
  jpeg-dev zlib-dev freetype-dev lcms2-dev openjpeg-dev tiff-dev tk-dev tcl-dev \
  bash git openssh \
  postgresql-dev
WORKDIR /server
COPY ./requirements.txt /server
RUN pip install -r requirements.txt && \
  pip install gunicorn
COPY . /server
VOLUME [ "/tmp", \
       "/server/static" ]
CMD [ "gunicorn", \
    "-b", \
    "unix:/tmp/gunicorn.sock", \
    "{{ cookiecutter.project_name }}.wsgi" ]
